# AFK Protection configuration

# Timer - # of seconds before a player is considered AFK
# Delay - # of seconds before /afk activates, anti-cheese
afk:
  timer: 300
  delay: 5

# Use %player% for display name, PlaceholderAPI optionally supported
# %delay% will only be parsed in messages.pending
messages:
  broadcast: true
  +afk: "&e%player% has gone afk"
  -afk: "&e%player% has returned"
  pending: "&7AFK in %delay% seconds..."
  canceled: "&4AFK canceled, you moved!"
  notaplayer: "&4Only players can be AFK!"

# Below option requires PlaceholderAPI
# %afkprot_status% - returns true or false, useful for things like the TAB plugin's conditions.
# %afkprot_tag% - returns tag if afk, recommended to use this over luckperms options
papi:
  status_true: "true"
  status_false: "false"
  tag: "&7[AFK]"

# Below options require LuckPerms
prefix:
  enabled: false
  value: "&7[AFK]"
  weight: 1

suffix:
  enabled: false
  value: "💤"
  weight: 1