# AFK Protection configuration

# Timer - # of seconds before a player is considered AFK
# Delay - # of seconds before /afk activates, anti-cheese
afk:
  timer: 120
  delay: 5

# Use %player% for display name
messages:
  enabled: true
  +afk: "%player% has gone afk"
  -afk: "%player% has returned"
  pending: "AFK in %delay% seconds..."
  canceled: "AFK canceled, you moved!"

# Below options require LuckPerms
prefix:
  enabled: false
  value: "[AFK]"
  weight: 1

suffix:
  enabled: false
  value: "💤"
  weight: 1