# AFK Protection configuration
afk:
  timer: 120

messages:
  enabled: true
  +afk: " has gone afk"
  -afk: " has returned"


# Below options require LuckPerms
prefix:
  enabled: false
  value: "[AFK]"
  weight: 1

suffix:
  enabled: false
  value: "💤"
  weight: 1