name: AFKProtection
version: '1.2-SNAPSHOT'
main: me.Gizzarduhh.afkProtection.AFKProtection
api-version: '1.21'
softdepend:
- LuckPerms
- PlaceholderAPI

commands:
  afk:
    description: Set yourself as AFK faster.
permissions:
  afkprotection.command.afk:
    default: true
    description: Use /afk command